name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        BUILD_TARGET: [release]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --profile ${{ matrix.BUILD_TARGET }} --verbose
    - name: Run tests
      run: cargo test --profile ${{ matrix.BUILD_TARGET }} --verbose
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: deepin-translation-utils
        path: target/${{ matrix.BUILD_TARGET }}/deepin-translation-utils
